name: Nightly Monitoring

on:
  schedule:
    - cron: '0 7 * * *'  # 7:00 UTC daily

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run monitoring (credit)
        run: |
          python -m src.jobs.run_monitoring --domain credit
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-reports
          path: reports/monitoring

